Return metadata from the `/meta` endpoint.
OnroerendErfgoed/storageprovider-client pull request #26
Opened 2021-11-17 10:34 UTC by Wim-De-Clercq

2021-11-17 13:20 UTC, claeyswo requested changes

2021-11-17 13:20 UTC, claeyswo commented on storageprovider/client.py
> +        result["Length"] = result["size"]  # backwards compatibility
Deze zou Content-Length moeten zijn denk ik: https://github.com/OnroerendErfgoed/plannen/blob/6040925083e5e93d6887e4bf9ac3c4ddd33de03e/plannen/search/index.py#L76

2021-11-17 13:20 UTC, claeyswo commented on storageprovider/client.py
> +        metadata["size"] = metadata["Length"]
Hier misschien ook nog Content-Type en Content-Length toevoegen voor bw compatibility?

2021-11-17 13:30 UTC, Wim-De-Clercq commented on storageprovider/client.py
> +        metadata["size"] = metadata["Length"]
hier is de logica andersom. De `res.headers` is wat de originele code was, dus die bevat al de content length en type. Ik voeg hier de mime en size toe om de `/meta` na te doen.
Het is dat, of ofwel een extra call te doen naar `/meta` om de 100% correcte metadata terug te geven.

2021-11-18 06:30 UTC, claeyswo approved these changes

2021-11-18 06:30 UTC, merged